// Generated by CoffeeScript 1.6.2
(function() {
  var Msg, mongoose;

  mongoose = require('mongoose');

  Msg = mongoose.model('Msgs');

  exports.list = function(req, res) {
    return Msg.find(function(err, Msgs) {
      return res.render('index', {
        title: 'Msg now!',
        Msgs: Msgs
      });
    });
  };

  exports.create = function(msg, next) {
    return new Msg({
      name: msg.name,
      content: msg.content,
      send_time: msg.send_time,
      created_time: Date()
    }).save(function(err, todo, count) {
      console.log("存好数据咯");
      return Msg.find(function(err, Msgs) {
        return next(err, Msgs);
      });
    });
  };

}).call(this);
